check:
  - overlays-build
overlays_dir: .
overlays:
  - name: digital-twin
    build:
      base-image: "quay.io/thoth-station/s2i-elyra-custom-notebook:v0.4.4"
      build-stratergy: Dockerfile
      dockerfile-path: Dockerfile.donkey
      custom-tag: latest
      registry: quay.io
      registry-org: aicoe
      registry-project: summit-2021-octo-keynote
      registry-secret: aicoe-pusher-secret
    deploy:
      project-org: "aicoe"
      project-name: "summit-2021-octo-keynote"
      image-name: "summit-2021-octo-keynote"
      overlay-contextpath: "templates/overlays/digital-twin/job.yaml"

  - name: raspberry-pi-edge-device
    build:
      build-stratergy: Dockerfile
      dockerfile-path: Dockerfile.donkey.arm64
      arch: arm64
      registry: quay.io
      registry-org: aicoe
      registry-project: summit-2021-octo-keynote
      registry-secret: aicoe-pusher-secret
    deploy:
      project-org: "aicoe"
      project-name: "summit-2021-octo-keynote"
      image-name: "summit-2021-octo-keynote"
      overlay-contextpath: "templates/overlays/raspberry-pi-edge/job.yaml"

  # uncomment when we have jetson edge device live
  # - name: jetson-edge-device
  #   build:
  #     build-stratergy: Dockerfile
  #     dockerfile-path: Dockerfile.donkey.arm64
  #     arch: arm64
  #     registry: quay.io
  #     registry-org: aicoe
  #     registry-project: summit-2021-octo-keynote
  #     registry-secret: aicoe-pusher-secret
  #   deploy:
  #     project-org: "aicoe"
  #     project-name: "summit-2021-octo-keynote"
  #     image-name: "summit-2021-octo-keynote"
  #     overlay-contextpath: "templates/overlays/jetson-edge/job.yaml"
