# Setup and configuring aicoe-ci with configuration file `.aicoe-ci.yaml`
# Example `.aicoe-ci.yaml` with a full list of config options is available here: https://github.com/AICoE/aicoe-ci/blob/master/docs/.aicoe-ci.yaml
---
check:
  - thoth-build
# Uncomment following lines to build a public image of this repo
build:
  build-stratergy: Dockerfile # Allowed values: Source, Dockerfile, Containerfile (default: Source)
  base-image: haoru233/tritonai-donkeycar:4.1-cpu # Temporary base img, will replace with our own
  dockerfile-path: apps/donkeycars/default_car/Dockerfile
  custom-tag: latest
  registry: quay.io
  registry-org: aicoe
  registry-project: summit-2021-octo-keynote
  registry-secret: aicoe-pusher-secret
