apiVersion: batch/v1
kind: Job
metadata:
  name: summit-2021-octo-keynote-v0.3.7
spec:
  template:
    metadata:
      labels:
        app: summit-2021-octo-keynote-webui
    spec:
      containers:
      - image: quay.io/aicoe/summit-2021-octo-keynote:v0.3.7-arm64
        livenessProbe:
          failureThreshold: 1
          initialDelaySeconds: 7200
          periodSeconds: 10
          tcpSocket:
            port: 80
        name: summit-2021-octo-keynote
        ports:
        - containerPort: 8887
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/vchiq
          name: dev-vchiq
        - mountPath: /dev/vcsm-cma
          name: dev-vcsm-cma
        - mountPath: /dev/i2c-1
          name: dev-i2c
        - mountPath: /dev/gpiomem
          name: dev-gpiomem
      restartPolicy: OnFailure
      volumes:
      - hostPath:
          path: /dev/vcsm-cma
        name: dev-vcsm-cma
      - hostPath:
          path: /dev/vchiq
        name: dev-vchiq
      - hostPath:
          path: /dev/i2c-1
        name: dev-i2c
      - hostPath:
          path: /dev/gpiomem
        name: dev-gpiomem
