apiVersion: v1
kind: Service
metadata:
  name: summit-2021-octo-keynote-port-service
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30100
    port: 8887
    protocol: TCP
    targetPort: 8887
  selector:
    app: summit-2021-octo-keynote-webui
  sessionAffinity: None
  type: NodePort
