kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rootdisk-pvc-microshift
  namespace: ushift-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
