apiVersion: batch/v1
kind: Job
metadata:
  name: summit-2021-octo-keynote
spec:
  template:
    spec:
      containers:
      - image: quay.io/aicoe/summit-2021-octo-keynote:test5
        livenessProbe:
          failureThreshold: 1
          initialDelaySeconds: 7200
          periodSeconds: 10
          tcpSocket:
            port: 80
        name: summit-2021-octo-keynote
      restartPolicy: OnFailure
